//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _HomeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _HomeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DniproFuture.Resources.Views.Home._HomeStrings", typeof(_HomeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про нас.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому ми допомогли.
        /// </summary>
        public static string ClientsTitle {
            get {
                return ResourceManager.GetString("ClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надіслати листа.
        /// </summary>
        public static string ContactsBtnTxt {
            get {
                return ResourceManager.GetString("ContactsBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зв&apos;яжіться з нами.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Майбутнє Дніпра.
        /// </summary>
        public static string HeaderDniproFuture {
            get {
                return ResourceManager.GetString("HeaderDniproFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочу знати більше.
        /// </summary>
        public static string HeaderMoreInfo {
            get {
                return ResourceManager.GetString("HeaderMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благодійна організація.
        /// </summary>
        public static string HeaderOrganization {
            get {
                return ResourceManager.GetString("HeaderOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Більше інформації.
        /// </summary>
        public static string HelpNowBtnTxt {
            get {
                return ResourceManager.GetString("HelpNowBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допомогти зараз.
        /// </summary>
        public static string HelpNowTitle {
            get {
                return ResourceManager.GetString("HelpNowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви маєте можливість допомогти саме зараз.
        /// </summary>
        public static string HelpNowTxt {
            get {
                return ResourceManager.GetString("HelpNowTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Речами.
        /// </summary>
        public static string HowClothing {
            get {
                return ResourceManager.GetString("HowClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформацією.
        /// </summary>
        public static string HowInformation {
            get {
                return ResourceManager.GetString("HowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грошима.
        /// </summary>
        public static string HowMoney {
            get {
                return ResourceManager.GetString("HowMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інше.
        /// </summary>
        public static string HowOther {
            get {
                return ResourceManager.GetString("HowOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Як Ви можете допомогти.
        /// </summary>
        public static string HowTitle {
            get {
                return ResourceManager.GetString("HowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про нас.
        /// </summary>
        public static string NavBarAbout {
            get {
                return ResourceManager.GetString("NavBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому допомогли.
        /// </summary>
        public static string NavBarClients {
            get {
                return ResourceManager.GetString("NavBarClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зв&apos;язок.
        /// </summary>
        public static string NavBarContacts {
            get {
                return ResourceManager.GetString("NavBarContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збір.
        /// </summary>
        public static string NavBarDonation {
            get {
                return ResourceManager.GetString("NavBarDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допомогти зараз.
        /// </summary>
        public static string NavBarHelpNow {
            get {
                return ResourceManager.GetString("NavBarHelpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Як допомогти.
        /// </summary>
        public static string NavBarHow {
            get {
                return ResourceManager.GetString("NavBarHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        public static string NavBarNews {
            get {
                return ResourceManager.GetString("NavBarNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнери.
        /// </summary>
        public static string NavBarPartners {
            get {
                return ResourceManager.GetString("NavBarPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнери.
        /// </summary>
        public static string PartnersTitle {
            get {
                return ResourceManager.GetString("PartnersTitle", resourceCulture);
            }
        }
    }
}
