//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _HomeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _HomeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DniproFuture.Resources.Views.Home._HomeStrings", typeof(_HomeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квітень 2015.
        /// </summary>
        public static string About_1_Date {
            get {
                return ResourceManager.GetString("About_1_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення.
        /// </summary>
        public static string About_1_SubTitle {
            get {
                return ResourceManager.GetString("About_1_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ми приступили до роботи і готові допомагати людям!.
        /// </summary>
        public static string About_1_Txt {
            get {
                return ResourceManager.GetString("About_1_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створимо&lt;br&gt;майбутнє&lt;br&gt;разом!.
        /// </summary>
        public static string AboutFuture {
            get {
                return ResourceManager.GetString("AboutFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про нас.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;h3&gt;Хто ми&lt;/h3&gt;&lt;br&gt;
        ///Ми - це благодійний фонд «Майбутнє Дніпра». Ми - це група небайдужих людей міста Дніпропетровськ. Ми - це організація, в яку ви завжди можете звернутися, якщо Вам чи Вашим близьким потрібна допомога або Ви самі маєте бажання надати допомогу іншим людям.&lt;/p&gt;
        ///&lt;p&gt;&lt;h3&gt;Наша мета&lt;/h3&gt;&lt;br&gt;
        ///Робота нашої організації спрямована на поліпшення життєвих умов як жителів усього міста Дніпропетровськ в цілому, так і на допомогу незахищеним верствам населення зокрема.&lt;/p&gt;.
        /// </summary>
        public static string AboutUsModalTxt {
            get {
                return ResourceManager.GetString("AboutUsModalTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому ми допомогли.
        /// </summary>
        public static string ClientsTitle {
            get {
                return ResourceManager.GetString("ClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надіслати листа.
        /// </summary>
        public static string ContactsBtnTxt {
            get {
                return ResourceManager.GetString("ContactsBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш Email .
        /// </summary>
        public static string ContactsEmailPH {
            get {
                return ResourceManager.GetString("ContactsEmailPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше повідомлення *.
        /// </summary>
        public static string ContactsMessagePH {
            get {
                return ResourceManager.GetString("ContactsMessagePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше ім&apos;я .
        /// </summary>
        public static string ContactsNamePH {
            get {
                return ResourceManager.GetString("ContactsNamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш номер телефону .
        /// </summary>
        public static string ContactsPhonePH {
            get {
                return ResourceManager.GetString("ContactsPhonePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше повідомлення було відіслано!.
        /// </summary>
        public static string ContactsSucces {
            get {
                return ResourceManager.GetString("ContactsSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зв&apos;яжіться з нами.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнати більше.
        /// </summary>
        public static string DonationMore {
            get {
                return ResourceManager.GetString("DonationMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цим людям потрібна допомога.
        /// </summary>
        public static string DonationSubTitle {
            get {
                return ResourceManager.GetString("DonationSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збір коштів.
        /// </summary>
        public static string DonationTitle {
            get {
                return ResourceManager.GetString("DonationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерея.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грн..
        /// </summary>
        public static string Grn {
            get {
                return ResourceManager.GetString("Grn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Майбутнє Дніпра.
        /// </summary>
        public static string HeaderDniproFuture {
            get {
                return ResourceManager.GetString("HeaderDniproFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочу знати більше.
        /// </summary>
        public static string HeaderMoreInfo {
            get {
                return ResourceManager.GetString("HeaderMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благодійна організація.
        /// </summary>
        public static string HeaderOrganization {
            get {
                return ResourceManager.GetString("HeaderOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Більше інформації.
        /// </summary>
        public static string HelpNowBtnTxt {
            get {
                return ResourceManager.GetString("HelpNowBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Благодійний фонд &quot;Майбутнє Дніпра&quot; буде вдячний за будь-яку фінансову та матеріальну допомогу. Пожертви будуть витрачені на реалізацію соціальних проектів фонду та на допомогу незахищеним верствам населення.&lt;br&gt;
        ///При переказі коштів, будь ласка, обов&apos;язково вкажіть позначку &quot;Благодійний внесок&quot;.&lt;/p&gt;.
        /// </summary>
        public static string HelpNowModalTxt {
            get {
                return ResourceManager.GetString("HelpNowModalTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви маєте можливість допомогти саме зараз.
        /// </summary>
        public static string HelpNowSubTitle {
            get {
                return ResourceManager.GetString("HelpNowSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допомогти зараз.
        /// </summary>
        public static string HelpNowTitle {
            get {
                return ResourceManager.GetString("HelpNowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благодійний фонд &quot;Майбутнє Дніпра&quot; буде вдячний за будь-яку фінансову та матеріальну допомогу. Пожертви будуть витрачені на реалізацію соціальних проектів фонду та на допомогу незахищеним верствам населення.&lt;/p&gt;.
        /// </summary>
        public static string HelpNowTxt {
            get {
                return ResourceManager.GetString("HelpNowTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одягом/Речами.
        /// </summary>
        public static string HowClothing {
            get {
                return ResourceManager.GetString("HowClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;У Вас в гардеробі скупчилися речі, які Ви не носите? Ви вирішили купити нові меблі і не знаєте що робити зі старими меблями? І Ви не знаєте кому б могли всі ці речі стати в нагоді?&lt;br&gt;
        ///Не поспішайте все це викидати! Адже речі, які здаються марними для вас, можуть бути корисні для інших людей! Наш фонд займається збором гуманітарної допомоги для жителів нашого міста. Тому, якщо у Вас є можливість, а головне бажання допомогти нужденним людям Дніпропетровська, то Ви можете це зробити самостійно або Ми може [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowClothingModalTxt {
            get {
                return ResourceManager.GetString("HowClothingModalTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ви володієте інформацією про людей, яким потрібна допомога?&lt;/p&gt;
        ///&lt;p&gt;Допомога потрібна Вам або комусь із ваших родичів?&lt;/p&gt;
        ///&lt;p&gt;Ви знаєте &amp;laquo;Як можна допомогти&amp;raquo; і &amp;laquo;Що потрібно робити&amp;raquo;, але не в силах реалізувати задумане самостійно?&lt;/p&gt;
        ///&lt;p&gt;Якщо Ви відповіли, хоча б на одне з питань позитивно, в такому випадку Вам варто зв&amp;#39;язатися з нами.&lt;/p&gt;
        ///&lt;p&gt;Ми - це БФ &amp;laquo;Майбутнє Дніпра&amp;raquo;. Ми надаємо матеріальну та юридичну допомогу людям Дніпропетровська. І нам потрібна Ваша допом [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowInfoModalTxt {
            get {
                return ResourceManager.GetString("HowInfoModalTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформацією.
        /// </summary>
        public static string HowInformation {
            get {
                return ResourceManager.GetString("HowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрити.
        /// </summary>
        public static string HowModalBtn {
            get {
                return ResourceManager.GetString("HowModalBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грошима.
        /// </summary>
        public static string HowMoney {
            get {
                return ResourceManager.GetString("HowMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Якщо у Вас є бажання і можливість зробити благодійний внесок, то нижче наведені реквізити нашого фонду. Кошти будуть витрачені на реалізацію проектів фонду.&lt;/p&gt;
        ///
        ///&lt;p&gt;В гривнях (UAH)&lt;br&gt;
        ///Отримувач: Благодійна организація «Майбутнє Дніпра» &lt;br&gt;
        ///Р/С: 26007050257995 в ПАТ КБ ПРИВАТБАНК&lt;br&gt;
        ///МФО: 305299&lt;br&gt;
        ///ЄДРПОУ: 39642709&lt;br&gt;
        ///Призначення платежа: «Благодійний внесок»&lt;/p&gt;.
        /// </summary>
        public static string HowMoneyModalTxt {
            get {
                return ResourceManager.GetString("HowMoneyModalTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інше.
        /// </summary>
        public static string HowOther {
            get {
                return ResourceManager.GetString("HowOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;На нашому сайті описано кілька способів для здійснення допомоги. Якщо Ви хочете запропонувати нам новий спосіб допомоги чи Ви бажаєте співпрацювати з нашим Благодійним Фондом, то, будь ласка, зв&amp;#39;яжіться з нами будь-яким зручним для Вас способом:&lt;br&gt;
        ///Тел: 096-823-32-02; 099-119-43-05&lt;br&gt;
        ///E-mail: info@dniprofuture.dp.ua&lt;br&gt;
        ///Skype: dniprofuture&lt;br&gt;
        ///Так само Ви можете просто заповнити заявку на нашому сайті, і ми обов&amp;#39;язково з вами зв&amp;#39;яжемося.&lt;/p&gt;.
        /// </summary>
        public static string HowOtherModalTxt {
            get {
                return ResourceManager.GetString("HowOtherModalTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Як Ви можете допомогти.
        /// </summary>
        public static string HowTitle {
            get {
                return ResourceManager.GetString("HowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше повідомлення надіслано успішно.
        /// </summary>
        public static string MessageSend {
            get {
                return ResourceManager.GetString("MessageSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про нас.
        /// </summary>
        public static string NavBarAbout {
            get {
                return ResourceManager.GetString("NavBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому допомогли.
        /// </summary>
        public static string NavBarClients {
            get {
                return ResourceManager.GetString("NavBarClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зв&apos;язок.
        /// </summary>
        public static string NavBarContacts {
            get {
                return ResourceManager.GetString("NavBarContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збір.
        /// </summary>
        public static string NavBarDonation {
            get {
                return ResourceManager.GetString("NavBarDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допомогти зараз.
        /// </summary>
        public static string NavBarHelpNow {
            get {
                return ResourceManager.GetString("NavBarHelpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Як допомогти.
        /// </summary>
        public static string NavBarHow {
            get {
                return ResourceManager.GetString("NavBarHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        public static string NavBarNews {
            get {
                return ResourceManager.GetString("NavBarNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнери.
        /// </summary>
        public static string NavBarPartners {
            get {
                return ResourceManager.GetString("NavBarPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекти.
        /// </summary>
        public static string NavBarProjects {
            get {
                return ResourceManager.GetString("NavBarProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детальніше....
        /// </summary>
        public static string NewsDetails {
            get {
                return ResourceManager.GetString("NewsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Більше новин.
        /// </summary>
        public static string NewsMore {
            get {
                return ResourceManager.GetString("NewsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Останні новини нашого фонду.
        /// </summary>
        public static string NewsSubTitle {
            get {
                return ResourceManager.GetString("NewsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірте вірність адресу E-mail.
        /// </summary>
        public static string NotEmail {
            get {
                return ResourceManager.GetString("NotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі партнери.
        /// </summary>
        public static string PartnersAll {
            get {
                return ResourceManager.GetString("PartnersAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Партнери.
        /// </summary>
        public static string PartnersTitle {
            get {
                return ResourceManager.GetString("PartnersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Більше проектів.
        /// </summary>
        public static string ProjectsMore {
            get {
                return ResourceManager.GetString("ProjectsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекти.
        /// </summary>
        public static string ProjectsTitle {
            get {
                return ResourceManager.GetString("ProjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Початок сбору.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Реквізити для переказу:&lt;/h4&gt;
        ///&lt;h5&gt;В гривнях (UAH)&lt;/h5&gt;
        ///Отримувач: Благодійна организація «Майбутнє Дніпра» &lt;br&gt;
        ///Р/С: 26007050257995 в ПАТ КБ ПРИВАТБАНК&lt;br&gt;
        ///МФО: 305299&lt;br&gt;
        ///ЄДРПОУ: 39642709&lt;br&gt;
        ///Призначення платежа: «Благодійний внесок»&lt;/p&gt;.
        /// </summary>
        public static string UAHInfo {
            get {
                return ResourceManager.GetString("UAHInfo", resourceCulture);
            }
        }
    }
}
