//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uh357966_dbEntities : DbContext
    {
        public uh357966_dbEntities()
            : base("name=uh357966_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }
        public virtual DbSet<NeedHelp> NeedHelp { get; set; }
        public virtual DbSet<NeedHelpLocalSet> NeedHelpLocalSet { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsLocalSet> NewsLocalSet { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<PartnersLocalSet> PartnersLocalSet { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ProjectsLocalSet> ProjectsLocalSet { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
