//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DniproFuture_siteEntities : DbContext
    {
        public DniproFuture_siteEntities()
            : base("name=DniproFuture_siteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<NeedHelp> NeedHelp { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<NeedHelpLocal> NeedHelpLocalSet { get; set; }
        public virtual DbSet<PartnersLocal> PartnersLocalSet { get; set; }
        public virtual DbSet<NewsLocal> NewsLocalSet { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ProjectsLocalSet> ProjectsLocalSet { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }

        public System.Data.Entity.DbSet<DniproFuture.Models.OutputModels.NeedHelpOutputModel> DonationOutputModels { get; set; }
    }
}
