//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.NeedHelpLocalSet = new HashSet<NeedHelpLocalSet>();
            this.NewsLocalSet = new HashSet<NewsLocalSet>();
            this.PartnersLocalSet = new HashSet<PartnersLocalSet>();
            this.ProjectsLocalSet = new HashSet<ProjectsLocalSet>();
        }
    
        public int Id { get; set; }
        public string LanguageCode { get; set; }
    
        public virtual ICollection<NeedHelpLocalSet> NeedHelpLocalSet { get; set; }
        public virtual ICollection<NewsLocalSet> NewsLocalSet { get; set; }
        public virtual ICollection<PartnersLocalSet> PartnersLocalSet { get; set; }
        public virtual ICollection<ProjectsLocalSet> ProjectsLocalSet { get; set; }
    }
}
