//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.NeedHelpLocal = new HashSet<NeedHelpLocal>();
            this.NewsLocal = new HashSet<NewsLocal>();
            this.PartnersLocal = new HashSet<PartnersLocal>();
        }
    
        public int Id { get; set; }
        public string LanguageCode { get; set; }
    
        public virtual ICollection<NeedHelpLocal> NeedHelpLocal { get; set; }
        public virtual ICollection<NewsLocal> NewsLocal { get; set; }
        public virtual ICollection<PartnersLocal> PartnersLocal { get; set; }
    }
}
