//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.NeedHelpLocal = new HashSet<NeedHelpLocal>();
            this.NewsLocal = new HashSet<NewsLocal>();
            this.PartnersLocal = new HashSet<PartnersLocal>();
            this.ProjectsLocalSet = new HashSet<ProjectsLocalSet>();
        }
    
        public int Id { get; set; }
        public string LanguageCode { get; set; }
    
        public virtual ICollection<NeedHelpLocal> NeedHelpLocal { get; set; }
        public virtual ICollection<NewsLocal> NewsLocal { get; set; }
        public virtual ICollection<PartnersLocal> PartnersLocal { get; set; }
        public virtual ICollection<ProjectsLocalSet> ProjectsLocalSet { get; set; }
    }
}
