//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeedHelp
    {
        public NeedHelp()
        {
            this.NeedHelpLocal = new HashSet<NeedHelpLocal>();
        }
    
        public int Id { get; set; }
        public int Sum { get; set; }
        public int NeedSum { get; set; }
        public string Photos { get; set; }
        public bool Done { get; set; }
    
        public virtual ICollection<NeedHelpLocal> NeedHelpLocal { get; set; }
    }
}
