//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsLocal
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public int NewsId { get; set; }
        public int LanguageId { get; set; }
    
        public virtual News News { get; set; }
        public virtual Language Language { get; set; }
    }
}
