//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.NewsLocalSet = new HashSet<NewsLocalSet>();
        }
    
        public int Id { get; set; }
        public string Images { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<NewsLocalSet> NewsLocalSet { get; set; }
    }
}
