//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.NewsLocal = new HashSet<NewsLocal>();
        }
    
        public int Id { get; set; }
        public string Images { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<NewsLocal> NewsLocal { get; set; }
    }
}
