//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DniproFuture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public Partners()
        {
            this.PartnersLocal = new HashSet<PartnersLocal>();
        }
    
        public int Id { get; set; }
        public string Logo { get; set; }
    
        public virtual ICollection<PartnersLocal> PartnersLocal { get; set; }
    }
}
